[package]
name = "chromepass"
version = "0.1.0"
authors = ["darkArp <mario@whitehathacking.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.25.3"
winapi = { version = "0.3.0", features = ["dpapi", "errhandlingapi"] }
base64 = "0.13.0"
aes-gcm = "0.8.0"
reqwest = { version = "*", features = ["blocking", "json"] }
serde_json = "1.0.59"
anyhow = "1.0"